version: '2'
services:
  db:
    image: postgres
    ports:
      - 5432:5432

  rota-acai:
    build: .
    command: bundle exec rails s -p 3002 -b '0.0.0.0'
    volumes:
      - .:/rota-acai
    ports:
      - 3002:3002
    links:
      - db
